import { AppRegistry } from 'react-native';
import HelloWorld from './components/HelloWorld';
import Robot from './components/Robot';
import MultipleGreetings from './components/MultipleGreetings';
import TextBlink from './components/TextBlink';
import Style from './components/Style';
import FixedDimension from './components/FixedDimension';
import FlexDimension from './components/FlexDimension';
import FlexExample from './components/FlexExample';
import JustifyContentExample from './components/JustifyContentExample';
import Touch from './components/Touch';
import Touchable from './components/Touchable';
import VerticalScrollView from './components/VerticalScrollView';
import HorizontalScrollView from './components/HorizontalScrollView';
import ViewPagerExample from './components/ViewPagerExample';
import BasicFlatList from './components/BasicFlatList';
import HorizontalFlatList from './components/HorizontalFlatList';
import BasicSectionList from './components/BasicSectionList';
import LifecycleComponent from './components/LifecycleComponent';
import App from './App';

AppRegistry.registerComponent('reactnative', () => BasicFlatList);
